name: Docker Image CI

on:
  push:
    branches: [ master, main ]
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'blabla...'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        tags: davyinsa/nginx
    - name: Build and push
      id: docker_build_subpath
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile-subpath
        tags: davyinsa/nginx:subpath
    - name: Login to ALIYUN CR
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUNCR_USERNAME }}
        password: ${{ secrets.ALIYUNCR_PASSWORD }}
    - name: Build and push to aliyun
      id: docker_build_aliyun
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile
        tags: registry.cn-hangzhou.aliyuncs.com/davyin/nginx
    - name: Build and push
      id: docker_build_aliyun_subpath
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: Dockerfile-subpath
        tags: registry.cn-hangzhou.aliyuncs.com/davyin/nginx:subpath
